spring.application.name=webbanhang

spring.profiles.active=local

spring.servlet.multipart.max-file-size=100MB

spring.jpa.hibernate.ddl-auto=update

# cho email, applog nua
logging.file.name=log/app.log
logging.pattern.file=%d %p %c{1.} [%t] %m%n

#logging.pattern.console=%d {HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=supervitmomo@gmail.com
spring.mail.password=jgyb nurr yvfu cwqa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


SECRET_KEY=