spring.application.name=webbanhang
spring.datasource.url=jdbc:mysql://localhost:3306/webbanhangsp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none